version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: crosschain-postgres
    environment:
      POSTGRES_DB: crosschain_ops
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: crosschain-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: crosschain-api
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:password123@postgres:5432/crosschain_ops
      REDIS_URL: redis://redis:6379
      PORT: 3000
      CORS_ORIGINS: http://localhost:3001
      CHAINS_CONFIG_PATH: /app/config/chains.json
      CONTRACTS_CONFIG_PATH: /app/config/contracts.json
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./config:/app/config:ro
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: